
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awsyqrhfzxyhtxhuwasu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3c3lxcmhmenh5aHR4aHV3YXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTA5ODMsImV4cCI6MjA1NjcyNjk4M30.KjWvFM_eaV3DeV3DatBfwZedMPy4EE6Vo2BHpuPW6MA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
